### ISSUE TITLE
Are instances of SwissEph class at all multi-thread safe?

### ISSUE THREAD

**Issue by barissaydag** [ygrenier/SwissEphNet#28]
Hi,

This is not a bug. 

I am developing a web application where multiple users will make queries. Ideally, I want to reduce the cost of initialization for each user. Within this context, I have three questions:
1) What is the overhead of creating a SwissEph class? 
2) Any concerns for creating multiple copies of it for multi-threaded use? For instance, do they depend on any static member variable that will get overwritten?
3) Are instances of SwissEph class at all multi-thread safe? For example, can I safely use rise_set function simultaneously from multiple threads using the same object?

Thanks a lot!
Baris

**Comment by ygrenier** [comment]
Hi,

As explains [here](https://github.com/ygrenier/SwissEphNet#thread-local-storage-tls-support), normally since the original library supports TLS, I removed all `static` fields/properties for having same behavior. So, unless I forgotten a few, each instance of the SwissEph is independent. 

But the class is not thread safe, it's most costly for a general behavior. It's more efficient to create one instance per thread, than having a thread safe instance.

If I run the tests on my old computer (6 years old) the average of the tests are running under 10ms and 35 Mb of memory (including the tests host management). 

If you look the [SwissEphNet samples project](https://github.com/ygrenier/SwissEphNet.Samples) and run some tests you can see the planets and houses calculation are under 50 ms (on my computer).

So I don't think it's a big problem to create a new instance for each web request. If you want create an ASP.NET Core Web application, you can register a scoped service to provide calculation without bad performance.

The real problem I detect for the moment, is the file access. If you want use the JPL or SwissEph files, you need to be sure to open the file on read mode and permitting the share access, in case of concurrent access. And I don't know which performance impact this can be cause.

Hoping this help you,

Regards
