### ISSUE TITLE
Missing constant SE_BIT_HINDU_RISING

### ISSUE THREAD

**Issue by quasar-pankaj** [ygrenier/SwissEphNet#36]
Hello Yan,
I was trying to calculate sunrise and sunset using swe_rise_trans with SE_BIT_HINDU_RISING
```
int rsmi = SwissEph.SE_CALC_RISE | SwissEph.SE_BIT_HINDU_RISING;
int return_code = eph.swe_rise_trans(tjd, ipl, starname, epheflag, rsmi, geopos, datm[0], datm[1], &trise, serr);
```
but that flag doesn't seem to be present. 
Can you tell me if there is a way to get it working or some work around?
Thanks,
Pankaj.

**Comment by ygrenier** [comment]
Hello,

Sorry for the delay, actually I've no computer and I've some professionnal problems, so I can't work on my personal projects.

Because I don't found the SE_BIT_HINDU_RISING flag in the code, I suppose it come with the version 2.7 of the Swiss Ephemeris.

The port of the version 2.7 was in progress when I lost my computer. So when I'll get a new computer and resolve some problems, I'll can continue the port work.

So in this case, there is no workaround for the moment.

I'm sorry for this situation, I hope I'll resolve my problems in few weeks.

Regards,

Yanos

**Comment by quasar-pankaj** [comment]
Sure. No problem. I'll wait for the next version.

**Comment by ygrenier** [comment]
Hi,

I just publish the PR #38 with the final portage for the version 2.07.01. But as explain I didn't have the time for tests.

If you can test the version in particular the SE_BIT_HINDU_RISING flag and make me some feeback, I'll appreciate.

Regards,

**Comment by ygrenier** [comment]
For information the version 2.08 is published.

**Comment by quasar-pankaj** [comment]
I will upgrade to the new version and test.

**Comment by quasar-pankaj** [comment]
The nuget is showing only 2.7.1 beta. So I have upgraded to it.

**Comment by ygrenier** [comment]
Could you retry, because the last version is available on [https://www.nuget.org/packages/SwissEphNet/](https://www.nuget.org/packages/SwissEphNet/) :
![image](https://user-images.githubusercontent.com/625432/60565502-2b48ea00-9d64-11e9-919a-8bb03acca371.png)

Regards

**Comment by quasar-pankaj** [comment]
Got it. The package manager took some time updating the list. I have updated to 2.8.0.1. I will try it out and report if there are any problems.
