### ISSUE TITLE
What is the current version of underlying SwissEph code?

### ISSUE THREAD

**Issue by barissaydag** [ygrenier/SwissEphNet#37]
SwissEph is now at version 2.7.1. Has this library been updated from original 2.6 to a later version? If so, what is the version?

**Comment by ygrenier** [comment]
Hello,

Actually I've no computer and I've some professionnal problems, so I can't work on my personal projects.

The current version of the SwissEphNet are base on the 2.6 version.

The 2.7.1 version port was in progress when I lost my computer. I hope I'll resolve my problems in few weeks, so at this time I'll could continue the 2.7.1 version port.

Regards,

Yanos

**Comment by ygrenier** [comment]
Hi,

I just open the PR #38 with the final portage of the version 2.07.01. But as explain I didn't a the time for tests. 

So if you the time to test the some new feature, I'll appreciate.

Regards,

Yanos

**Comment by barissaydag** [comment]
I will test it as soon as possible. Thanks a lot Yanos, you are awesome!

**Comment by ygrenier** [comment]
Because the new version 2.08 is available, I published the [version 2.7.1.3 (2.07.01)](https://github.com/ygrenier/SwissEphNet/releases/tag/v2.7.1.3)  before working to the new version.

The PR #38 is closed.

I don't know when I'll could work on the new version (I don't know if it's a lot of work to do).
